### ISSUE TITLE
How to manually set-up a youtube profile?

### ISSUE THREAD

**Issue by GWD72** [celenityy/Phoenix#5]
I would like to make use of the `youtube.cfg` and give youtube a go with Phoenix, but I've no idea where to put the file, and what else it needs, if already using the non-hardened version, on Linux and windows. If other files are required in the downloadable .zip file, and of those, there are multiple versions with the same file name, please indicate which directories they'll be found in.

**Comment by celenityy** [comment]
Thank you for the issue!

This is something we definitely need to document, especially for manual installations. Top priority and will get back to you shortly once steps are ready.

**Comment by celenityy** [comment]
I’ll make more proper documentation shortly, but for now, here’s the steps. These steps are also the same for any other specialized config we offer (ex. Hardened), simply replace mentions of `youtube` below with the config of choice.

1. Download `youtube.cfg` from [here](https://github.com/celenityy/Phoenix/raw/refs/heads/pages/configs/youtube.cfg).

2. Store the file in a safe, easy to remember location. It doesn’t particularly matter where, but I’d advise if possible setting it somewhere where it can’t easily be edited. By default, on Linux, `youtube.cfg` is located at `/etc/firefox/phoenix/configs/youtube.cfg`, so I’ll use that directory as an example in the following comments. You can replace it with wherever you actually decide to store the file. *(These same steps should also apply for Windows)*.

3. Create a new, empty `user.js` file via your text editor, and give it the following content:

```sh
user_pref("autoadmin.global_config_url", "file:///etc/firefox/phoenix/configs/youtube.cfg");
```

(You can also download our template user.js file from [here](https://github.com/celenityy/Phoenix/raw/refs/heads/pages/userjs/linux/youtube/user.js) if you’d like).

4. Assuming you didn’t store `youtube.cfg` in the default location, *(or you’re on Windows…)*, replace `/etc/firefox/phoenix/configs/youtube.cfg` on the `user.js` with the actual location where you stored `youtube.cfg`. Just be sure to leave `file://` at the start.

5. Move `user.js` to your Firefox profile’s directory *(You can find it via Step 3 [here](https://github.com/celenityy/Phoenix/tree/pages?tab=readme-ov-file#complete-coverage)*.

6. Profit. Just make sure to keep an eye on and update the `youtube.cfg` file as we improve it (Same as you would for any other part of Phoenix).

**Comment by GWD72** [comment]
Great, thanks! And never any rush, but thanks for the fast action and extremely clear instructions!

**Comment by GWD72** [comment]
So the install works fine, but if I would want to, I don't see a way to toggle configs, such that I would be able to login (I tried by disabling `configs` under that heading in the `youtube.cfg`file, but that was not enough. I don't generally do that (sometimes for comments, but never when watching) but some users might more often. Of course, in that case, one has already kissed the ring of google, so I suppose using `youtube.cfg` then would be moot, and such users would be better off just using their usual Firefox profile.

As for FreeTuibe, I think it is fine using a vpn and viewing videos using mpv player privacy-wise. I find (like chrome) I cannot get FreeTube to utilise the iGPU, but can force mpv player to do so, which saves battery and high-temps on a laptop.
